"""remove skill_id from topic

Revision ID: 109a81e5f024
Revises: 
Create Date: 2026-04-29 03:29:05.365109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109a81e5f024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ✅ REMOVE FK FIRST
    op.drop_constraint(op.f('topic_skill_id_fkey'), 'topic', type_='foreignkey')

    # ✅ REMOVE COLUMN
    op.drop_column('topic', 'skill_id')

    # ✅ REMOVE SKILL TABLE
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_table('skill')

    # ❌ DO NOT TOUCH level / created_at again (already exists)

    # ✅ OTHER SAFE OPS
    op.create_foreign_key(None, 'session', 'topic', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'session', 'user', ['learner_id'], ['id'])
    op.create_foreign_key(None, 'session', 'user', ['tutor_id'], ['id'])

    op.create_foreign_key(None, 'testattempt', 'topic', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'testattempt', 'user', ['user_id'], ['id'])

    op.alter_column('user', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    op.alter_column('userskill', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userskill', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'bio',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('topic', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('topic_skill_id_fkey'), 'topic', 'skill', ['skill_id'], ['id'])
    op.drop_constraint(None, 'testattempt', type_='foreignkey')
    op.drop_constraint(None, 'testattempt', type_='foreignkey')
    op.drop_column('testattempt', 'created_at')
    op.drop_column('testattempt', 'level')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.alter_column('session', 'learner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('session', 'start_time')
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=False)
    # ### end Alembic commands ###
