"""add meeting fields

Revision ID: 1d1f4b60cd25
Revises: e82024392425
Create Date: 2026-07-07 21:39:36.853045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d1f4b60cd25'
down_revision: Union[str, Sequence[str], None] = 'e82024392425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        "session",
        sa.Column("meeting_room_id", sa.String(), nullable=True)
    )

    op.add_column(
        "session",
        sa.Column("meeting_room", sa.String(), nullable=True)
    )

    op.add_column(
        "session",
        sa.Column("meeting_link", sa.String(), nullable=True)
    )

    op.add_column(
        "session",
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            server_default="open"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'status')
    op.drop_column('session', 'meeting_link')
    op.drop_column('session', 'meeting_room')
    op.drop_column('session', 'meeting_room_id')
    # ### end Alembic commands ###
