"""add level to testattemptclear

Revision ID: b72c73e00db5
Revises: 109a81e5f024
Create Date: 2026-05-01 02:34:12.815823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72c73e00db5'
down_revision: Union[str, Sequence[str], None] = '109a81e5f024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ✅ session change
    op.add_column('session', sa.Column('start_time', sa.DateTime(), nullable=False))

    op.alter_column('session', 'learner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ✅ level column (already correct)
    op.add_column(
        'testattempt',
        sa.Column('level', sa.String(), nullable=False, server_default='beginner')
    )

    op.alter_column('testattempt', 'level', server_default=None)

    # ✅ created_at FIXED
    op.add_column(
        'testattempt',
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
    )

    op.alter_column('testattempt', 'created_at', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testattempt', 'created_at')
    op.drop_column('testattempt', 'level')
    op.alter_column('session', 'learner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('session', 'start_time')
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=False)
    # ### end Alembic commands ###
