"""token based

Revision ID: bb78c4fb78c6
Revises: b72c73e00db5
Create Date: 2026-06-09 14:11:34.513044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb78c4fb78c6'
down_revision: Union[str, Sequence[str], None] = 'b72c73e00db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=False)
    # ### end Alembic commands ###
