"""add availability slot id

Revision ID: e82024392425
Revises: 070c4b7edf56
Create Date: 2026-07-05 22:28:57.754893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82024392425'
down_revision: Union[str, Sequence[str], None] = '070c4b7edf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('availability_slot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'availabilityslot', ['availability_slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'availability_slot_id')
    # ### end Alembic commands ###
